# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    base_path_dir: '%kernel.project_dir%/public/'
    picture_directory: 'images'
    icon_directory: 'icons'
    video_directory: 'videos'
    document_directory: 'documents'
    site_url: '%env(resolve:SITE_URL)%'
    currency: '%env(resolve:TARGET_CURRENCY)%'
    taxe_rate: '%env(resolve:TAXE_RATE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    ###> EventListener configuration
    App\EventListener\AuthenticationSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }

    App\EventListener\CorsListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    ###< EventListener configuration

    App\State\:
        resource: '../src/State/'
        autowire: true
        autoconfigure: true
        public: true
        tags: ['api_platform.state_processor']

    # Explicitly configure the "Service" directory as a service
    App\Service\:
        resource: '../src/Service/'
        autowire: true
        autoconfigure: true
        public: true

    App\DataProvider\:
        resource: '../src/DataProvider/'
        autowire: true
        autoconfigure: true
        public: true

    App\Security\:
        resource: '../src/Security/'
        autowire: true
        autoconfigure: true
        public: true

    App\Filter\:
        resource: '../src/Filter/'
        autowire: true
        autoconfigure: true
        public: true

    App\Command\ProcessEmailQueueCommand:
        arguments:
            $environment: '%env(APP_ENV)%'
            $batchSize: '%env(int:EMAIL_QUEUE_BATCH_SIZE)%'


    App\Service\BrightDataAmazonScraper:
        arguments:
            $brightDataApiKey: '%env(BRIGHT_DATA_API_KEY)%'

    App\Service\ExchangeRateApiService:
        arguments:
            $exchangeRateApiKey: '%env(EXCHANGE_RATE_API_KEY)%'


    App\Entity\Product:
        arguments:
            $currency: '%env(TARGET_CURRENCY)%'
            $taxRate: '%env(TAXE_RATE)%'

    App\Security\GoogleAuthenticator:
        arguments:
            $googleClientId: '%env(GOOGLE_CLIENT_ID)%'

    App\Service\BrevoEmailService:
        arguments:
            $mailer: '@Symfony\Component\Mailer\MailerInterface'
            $fromEmail: '%env(MAILER_FROM)%'
            $fromName: '%env(MAILER_FROM_NAME)%'
            $apiKey: '%env(BREVO_API_KEY)%'
        tags: ['monolog.logger']

    gesdinet.jwtrefreshtoken:
        class: Gesdinet\JWTRefreshTokenBundle\Service\RefreshToken
        arguments:
            - '@gesdinet.jwtrefreshtoken.refresh_token_manager'
            - '@lexik_jwt_authentication.jwt_manager'
            - '@gesdinet.jwtrefreshtoken.generator'
            - '@gesdinet.jwtrefreshtoken.request.extractor'
            - '@event_dispatcher'

    ###> Filters 
    categories.search_filter:
      parent: 'api_platform.doctrine.orm.search_filter'
      arguments: [{title: 'partial'}]
      tags:
          - { name: api_platform.filter }

    products.search_filter:
      parent: 'api_platform.doctrine.orm.search_filter'
      arguments: [{title: 'partial', slug: 'exact', isAvailable: 'exact', category.title: 'exact'}]
      tags:
          - { name: api_platform.filter }

    products.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments: [{createdAt: 'asc', usdPrice: 'asc'}]
        tags:
            - { name: api_platform.filter }

    my_order.search_filter:
      parent: 'api_platform.doctrine.orm.search_filter'
      arguments: [{uid: 'partial', status: 'exact'}]
      tags:
          - { name: api_platform.filter }

    my_order.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments: [{createdAt: 'asc'}]
        tags:
          - { name: api_platform.filter }

    my_basket.search_filter:
      parent: 'api_platform.doctrine.orm.search_filter'
      arguments: [{uid: 'exact'}]
      tags:
          - { name: api_platform.filter }
    ###< Filters 

    App\Service\EmailQueueService:
        arguments:
            $frontendURL: '%env(FRONTEND_URL)%'
            $websiteName: '%env(WEBSITE_NAME)%'
            $passwordResetTemplateId: '%env(PASSWORD_RESET_TEMPLATE_ID)%'
            $emailConfirmationTemplateId: '%env(EMAIL_CONFIRMATION_TEMPLATE_ID)%'
            $passwordChangedTemplateId: '%env(PASSWORD_CHANGED_TEMPLATE_ID)%'